### ISSUE TITLE
Witryna Projektu

### ISSUE THREAD

**Issue by agnieszkadrozdek** [oramm/Moje.ENVI#6]
[prt sc witryna 04.01.2019..docx](https://github.com/oramm/Moje.ENVI/files/2726657/prt.sc.witryna.04.01.2019.docx)

**Comment by oramm** [comment]
ten błąd już jest naprawiony

**Comment by agnieszkadrozdek** [comment]
Brak możliwości zarejestrowania umowy, gdy na GD istnieje struktura folderów dla danego - rejestrowanego tematu.
