### ISSUE TITLE
Wprowadzenie Podmiotu

### ISSUE THREAD

**Issue by agnieszkadrozdek** [oramm/Moje.ENVI#7]
Brak możliwości wprowadzenia Podmiotu w celu wprowadzenia kontaktu.

**Comment by oramm** [comment]
Poprawione. 
@agnieszkadrozdek potwierdź czy działa

**Comment by oramm** [comment]
@agnieszkadrozdek Teraz powinno być ok, potwierdź działanie, Jeśli nie to pisz tutaj uwagi.

**Comment by oramm** [comment]
@agnieszkadrozdek  Nic nie piszesz, więc uznaję, że problemu już nie ma. W przyszłości odpowiadaj na zaczepki :).
